version: "1.0"

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: Pa$$w0rd
      MYSQL_DATABASE: db_user
      MYSQL_USER: appuser
      MYSQL_PASSWORD: Pa$$w0rd
    command: >
      mysqld --default-authentication-plugin=mysql_native_password
             --character-set-server=utf8mb4
             --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app_net

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      NODE_ENV: DEV
      PORT: 3000
      MYSQL_HOST: localhost
      MYSQL_USER: appuser
      MYSQL_PASSWORD: Pa$$w0rd
      MYSQL_DATABASE: db_annonces
    depends_on:
      db:
       condition: service_healthy
    expose:
      - "3000"
    networks:
      - app_net

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      server:
       condition: service_healthy

volumes:
  db_data:


networks:
  app_net:
    driver: bridge